### ISSUE TITLE
add target parameter to zwave firmware update

### ISSUE THREAD

**Issue by joeroback** [djdizzyd/hubitat#4]
Hi. Would it be possible to add target to z-wave updater driver? The inovelli switches and dimmers with LED bar have a separate firmware (target 1) for the LED bar.

https://support.inovelli.com/portal/kb/articles/firmware-v1-43-beta-lzw31-sn-dimmer-red-series-gen-2

Thanks

**Comment by djdizzyd** [comment]
The target is automatically selected based on matching firmware descriptor.. the issue with this one is the MCU they used doesn't match established z-wave standards for firmware descriptor location and I can't find any documentation on this MCU and their firmware file format

**Comment by joeroback** [comment]
ok well in Z Wave PC controller, you can just select Target 1.

![image](https://user-images.githubusercontent.com/156174/83046749-ab271500-a004-11ea-9e20-cb3af6025d6b.png)

Slightly bad screenshot, as this only shows target 0, but with the inovelli dimmers, it shows Target 0, Target 1

Bummer I guess.

**Comment by MFornander** [comment]
This seems like a really nice feature since there are a lot of Inovelli devices out there.  Please re-open this issue.
